db.students.insertMany([
  {
    name: "Aarav Sharma",
    class: 10,
    age: 15,
    gender: "Male",
    rollNo: 101,
    city: "Delhi",
    marks: { math: 88, science: 92, english: 85, hindi: 90 },
    totalMarks: 355,
    percentage: 88.75,
    grade: "A",
    attendance: 92,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Reading"],
    skills: ["Communication", "Problem Solving"]
  },

  {
    name: "Priya Verma",
    class: 12,
    age: 17,
    gender: "Female",
    rollNo: 102,
    city: "Lucknow",
    marks: { math: 95, science: 91, english: 94, hindi: 96 },
    totalMarks: 376,
    percentage: 94,
    grade: "A+",
    attendance: 97,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Dancing", "Painting"],
    skills: ["Leadership", "Communication"]
  },

  {
    name: "Rohan Singh",
    class: 8,
    age: 13,
    gender: "Male",
    rollNo: 103,
    city: "Dehradun",
    marks: { math: 72, science: 78, english: 81, hindi: 75 },
    totalMarks: 306,
    percentage: 76.5,
    grade: "B+",
    attendance: 88,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Football", "Gaming"],
    skills: ["Teamwork", "Creativity"]
  },

  {
    name: "Ananya Gupta",
    class: 11,
    age: 16,
    gender: "Female",
    rollNo: 104,
    city: "Jaipur",
    marks: { math: 91, physics: 89, chemistry: 93, english: 87 },
    totalMarks: 360,
    percentage: 90,
    grade: "A+",
    attendance: 95,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Music"],
    skills: ["Research", "Communication"]
  },

  {
    name: "Vikash Kumar",
    class: 9,
    age: 14,
    gender: "Male",
    rollNo: 105,
    city: "Patna",
    marks: { math: 65, science: 70, english: 68, hindi: 74 },
    totalMarks: 277,
    percentage: 69.25,
    grade: "B",
    attendance: 82,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Cycling"],
    skills: ["Teamwork"]
  },

  {
    name: "Neha Joshi",
    class: 10,
    age: 15,
    gender: "Female",
    rollNo: 106,
    city: "Dehradun",
    marks: { math: 89, science: 95, english: 91, hindi: 88 },
    totalMarks: 363,
    percentage: 90.75,
    grade: "A+",
    attendance: 96,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Singing", "Reading"],
    skills: ["Leadership", "Creativity"]
  },

  {
    name: "Rahul Mehta",
    class: 12,
    age: 18,
    gender: "Male",
    rollNo: 107,
    city: "Mumbai",
    marks: { math: 82, physics: 86, chemistry: 80, english: 89 },
    totalMarks: 337,
    percentage: 84.25,
    grade: "A",
    attendance: 90,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Football", "Photography"],
    skills: ["Leadership", "Problem Solving"]
  },

  {
    name: "Sneha Patel",
    class: 7,
    age: 12,
    gender: "Female",
    rollNo: 108,
    city: "Ahmedabad",
    marks: { math: 76, science: 82, english: 79, hindi: 84 },
    totalMarks: 321,
    percentage: 80.25,
    grade: "A",
    attendance: 91,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Painting", "Dancing"],
    skills: ["Creativity"]
  },

  {
    name: "Aditya Mishra",
    class: 10,
    age: 15,
    gender: "Male",
    rollNo: 109,
    city: "Kanpur",
    marks: { math: 97, science: 90, english: 88, hindi: 92 },
    totalMarks: 367,
    percentage: 91.75,
    grade: "A+",
    attendance: 98,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Coding", "Chess"],
    skills: ["Programming", "Problem Solving"]
  },

  {
    name: "Kavya Singh",
    class: 9,
    age: 14,
    gender: "Female",
    rollNo: 110,
    city: "Khatima",
    marks: { math: 85, science: 87, english: 90, hindi: 86 },
    totalMarks: 348,
    percentage: 87,
    grade: "A",
    attendance: 93,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Music", "Reading"],
    skills: ["Communication", "Creativity"]
  },

  {
    name: "Arjun Kapoor",
    class: 11,
    age: 17,
    gender: "Male",
    rollNo: 111,
    city: "Delhi",
    marks: { math: 93, physics: 94, chemistry: 89, english: 85 },
    totalMarks: 361,
    percentage: 90.25,
    grade: "A+",
    attendance: 94,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Cricket", "Coding"],
    skills: ["Programming", "Leadership"]
  },

  {
    name: "Ishita Roy",
    class: 8,
    age: 13,
    gender: "Female",
    rollNo: 112,
    city: "Kolkata",
    marks: { math: 78, science: 85, english: 88, hindi: 80 },
    totalMarks: 331,
    percentage: 82.75,
    grade: "A",
    attendance: 89,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Dancing", "Singing"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Mohit Yadav",
    class: 12,
    age: 18,
    gender: "Male",
    rollNo: 113,
    city: "Gurgaon",
    marks: { math: 76, physics: 82, chemistry: 78, english: 80 },
    totalMarks: 316,
    percentage: 79,
    grade: "B+",
    attendance: 85,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Football", "Gaming"],
    skills: ["Teamwork"]
  },

  {
    name: "Pooja Agarwal",
    class: 10,
    age: 15,
    gender: "Female",
    rollNo: 114,
    city: "Agra",
    marks: { math: 92, science: 89, english: 95, hindi: 93 },
    totalMarks: 369,
    percentage: 92.25,
    grade: "A+",
    attendance: 97,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Reading", "Painting"],
    skills: ["Research", "Communication"]
  },

  {
    name: "Karan Thakur",
    class: 6,
    age: 11,
    gender: "Male",
    rollNo: 115,
    city: "Shimla",
    marks: { math: 68, science: 72, english: 75, hindi: 70 },
    totalMarks: 285,
    percentage: 71.25,
    grade: "B",
    attendance: 87,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Drawing"],
    skills: ["Teamwork"]
  },

  {
    name: "Simran Kaur",
    class: 9,
    age: 14,
    gender: "Female",
    rollNo: 116,
    city: "Amritsar",
    marks: { math: 88, science: 91, english: 86, hindi: 90 },
    totalMarks: 355,
    percentage: 88.75,
    grade: "A",
    attendance: 94,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Singing", "Reading"],
    skills: ["Communication", "Leadership"]
  },

  {
    name: "Nitin Sharma",
    class: 8,
    age: 13,
    gender: "Male",
    rollNo: 117,
    city: "Chandigarh",
    marks: { math: 81, science: 77, english: 83, hindi: 79 },
    totalMarks: 320,
    percentage: 80,
    grade: "A",
    attendance: 90,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cycling", "Football"],
    skills: ["Teamwork", "Creativity"]
  },

  {
    name: "Meera Nair",
    class: 11,
    age: 16,
    gender: "Female",
    rollNo: 118,
    city: "Kochi",
    marks: { math: 96, physics: 92, chemistry: 95, english: 91 },
    totalMarks: 374,
    percentage: 93.5,
    grade: "A+",
    attendance: 99,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Music"],
    skills: ["Research", "Problem Solving"]
  },

  {
    name: "Ravi Kumar",
    class: 7,
    age: 12,
    gender: "Male",
    rollNo: 119,
    city: "Lucknow",
    marks: { math: 62, science: 69, english: 71, hindi: 76 },
    totalMarks: 278,
    percentage: 69.5,
    grade: "B",
    attendance: 80,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Gaming"],
    skills: ["Teamwork"]
  },

  {
    name: "Diya Malhotra",
    class: 12,
    age: 17,
    gender: "Female",
    rollNo: 120,
    city: "Jaipur",
    marks: { math: 90, physics: 88, chemistry: 92, english: 94 },
    totalMarks: 364,
    percentage: 91,
    grade: "A+",
    attendance: 96,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Dancing", "Painting"],
    skills: ["Leadership", "Creativity"]
  },

  {
    name: "Sahil Khan",
    class: 10,
    age: 15,
    gender: "Male",
    rollNo: 121,
    city: "Bhopal",
    marks: { math: 79, science: 84, english: 77, hindi: 82 },
    totalMarks: 322,
    percentage: 80.5,
    grade: "A",
    attendance: 88,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Football", "Photography"],
    skills: ["Teamwork"]
  },

  {
    name: "Nisha Rawat",
    class: 9,
    age: 14,
    gender: "Female",
    rollNo: 122,
    city: "Haldwani",
    marks: { math: 94, science: 90, english: 92, hindi: 95 },
    totalMarks: 371,
    percentage: 92.75,
    grade: "A+",
    attendance: 98,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Reading", "Singing"],
    skills: ["Communication", "Leadership"]
  },

  {
    name: "Varun Joshi",
    class: 12,
    age: 18,
    gender: "Male",
    rollNo: 123,
    city: "Dehradun",
    marks: { math: 87, physics: 91, chemistry: 85, english: 88 },
    totalMarks: 351,
    percentage: 87.75,
    grade: "A",
    attendance: 91,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Coding", "Chess"],
    skills: ["Programming", "Problem Solving"]
  },

  {
    name: "Riya Gupta",
    class: 6,
    age: 11,
    gender: "Female",
    rollNo: 124,
    city: "Noida",
    marks: { math: 73, science: 78, english: 82, hindi: 79 },
    totalMarks: 312,
    percentage: 78,
    grade: "B+",
    attendance: 86,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Drawing", "Dancing"],
    skills: ["Creativity"]
  },

  {
    name: "Akash Verma",
    class: 8,
    age: 13,
    gender: "Male",
    rollNo: 125,
    city: "Bareilly",
    marks: { math: 90, science: 86, english: 84, hindi: 88 },
    totalMarks: 348,
    percentage: 87,
    grade: "A",
    attendance: 93,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Coding"],
    skills: ["Programming", "Teamwork"]
  },

  {
    name: "Tanvi Sharma",
    class: 10,
    age: 15,
    gender: "Female",
    rollNo: 126,
    city: "Delhi",
    marks: { math: 98, science: 96, english: 94, hindi: 97 },
    totalMarks: 385,
    percentage: 96.25,
    grade: "A+",
    attendance: 99,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Reading", "Chess"],
    skills: ["Leadership", "Problem Solving"]
  },

  {
    name: "Manish Rawat",
    class: 7,
    age: 12,
    gender: "Male",
    rollNo: 127,
    city: "Rishikesh",
    marks: { math: 70, science: 74, english: 69, hindi: 72 },
    totalMarks: 285,
    percentage: 71.25,
    grade: "B",
    attendance: 83,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Football", "Cycling"],
    skills: ["Teamwork"]
  },

  {
    name: "Aisha Khan",
    class: 11,
    age: 16,
    gender: "Female",
    rollNo: 128,
    city: "Hyderabad",
    marks: { math: 89, physics: 87, chemistry: 91, english: 93 },
    totalMarks: 360,
    percentage: 90,
    grade: "A+",
    attendance: 95,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Painting", "Music"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Deepak Yadav",
    class: 9,
    age: 14,
    gender: "Male",
    rollNo: 129,
    city: "Kanpur",
    marks: { math: 75, science: 80, english: 78, hindi: 73 },
    totalMarks: 306,
    percentage: 76.5,
    grade: "B+",
    attendance: 87,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Gaming"],
    skills: ["Teamwork"]
  },

  {
    name: "Muskan Singh",
    class: 12,
    age: 18,
    gender: "Female",
    rollNo: 130,
    city: "Varanasi",
    marks: { math: 93, physics: 95, chemistry: 90, english: 96 },
    totalMarks: 374,
    percentage: 93.5,
    grade: "A+",
    attendance: 98,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Singing"],
    skills: ["Leadership", "Research"]
  },

  {
    name: "Yash Patel",
    class: 10,
    age: 15,
    gender: "Male",
    rollNo: 131,
    city: "Ahmedabad",
    marks: { math: 84, science: 88, english: 82, hindi: 86 },
    totalMarks: 340,
    percentage: 85,
    grade: "A",
    attendance: 92,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Coding", "Cricket"],
    skills: ["Programming", "Problem Solving"]
  },

  {
    name: "Shreya Das",
    class: 8,
    age: 13,
    gender: "Female",
    rollNo: 132,
    city: "Kolkata",
    marks: { math: 91, science: 87, english: 94, hindi: 89 },
    totalMarks: 361,
    percentage: 90.25,
    grade: "A+",
    attendance: 96,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Dancing", "Painting"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Aman Singh",
    class: 6,
    age: 11,
    gender: "Male",
    rollNo: 133,
    city: "Khatima",
    marks: { math: 66, science: 71, english: 68, hindi: 74 },
    totalMarks: 279,
    percentage: 69.75,
    grade: "B",
    attendance: 81,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Drawing"],
    skills: ["Teamwork"]
  },

  {
    name: "Pallavi Mehra",
    class: 11,
    age: 17,
    gender: "Female",
    rollNo: 134,
    city: "Pune",
    marks: { math: 97, physics: 93, chemistry: 96, english: 92 },
    totalMarks: 378,
    percentage: 94.5,
    grade: "A+",
    attendance: 99,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Coding"],
    skills: ["Programming", "Research"]
  },

  {
    name: "Ritesh Kumar",
    class: 9,
    age: 14,
    gender: "Male",
    rollNo: 135,
    city: "Patna",
    marks: { math: 83, science: 79, english: 81, hindi: 77 },
    totalMarks: 320,
    percentage: 80,
    grade: "A",
    attendance: 89,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Football", "Gaming"],
    skills: ["Teamwork", "Creativity"]
  },

  {
    name: "Sakshi Gupta",
    class: 10,
    age: 15,
    gender: "Female",
    rollNo: 136,
    city: "Lucknow",
    marks: { math: 90, science: 94, english: 91, hindi: 89 },
    totalMarks: 364,
    percentage: 91,
    grade: "A+",
    attendance: 97,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Singing", "Reading"],
    skills: ["Communication", "Leadership"]
  },

  {
    name: "Harsh Vardhan",
    class: 12,
    age: 18,
    gender: "Male",
    rollNo: 137,
    city: "Delhi",
    marks: { math: 86, physics: 89, chemistry: 84, english: 87 },
    totalMarks: 346,
    percentage: 86.5,
    grade: "A",
    attendance: 90,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Coding", "Chess"],
    skills: ["Programming", "Problem Solving"]
  },

  {
    name: "Nandini Rao",
    class: 7,
    age: 12,
    gender: "Female",
    rollNo: 138,
    city: "Bangalore",
    marks: { math: 88, science: 85, english: 90, hindi: 87 },
    totalMarks: 350,
    percentage: 87.5,
    grade: "A",
    attendance: 94,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Painting", "Dancing"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Rajat Mishra",
    class: 8,
    age: 13,
    gender: "Male",
    rollNo: 139,
    city: "Prayagraj",
    marks: { math: 74, science: 76, english: 72, hindi: 80 },
    totalMarks: 302,
    percentage: 75.5,
    grade: "B+",
    attendance: 84,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Cycling"],
    skills: ["Teamwork"]
  },

  {
    name: "Komal Sharma",
    class: 9,
    age: 14,
    gender: "Female",
    rollNo: 140,
    city: "Jaipur",
    marks: { math: 95, science: 92, english: 90, hindi: 94 },
    totalMarks: 371,
    percentage: 92.75,
    grade: "A+",
    attendance: 98,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Reading", "Music"],
    skills: ["Leadership", "Research"]
  },

  {
    name: "Suresh Kumar",
    class: 6,
    age: 11,
    gender: "Male",
    rollNo: 141,
    city: "Agra",
    marks: { math: 59, science: 65, english: 70, hindi: 68 },
    totalMarks: 262,
    percentage: 65.5,
    grade: "B",
    attendance: 79,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Football", "Gaming"],
    skills: ["Teamwork"]
  },

  {
    name: "Isha Kapoor",
    class: 10,
    age: 15,
    gender: "Female",
    rollNo: 142,
    city: "Mumbai",
    marks: { math: 87, science: 91, english: 96, hindi: 90 },
    totalMarks: 364,
    percentage: 91,
    grade: "A+",
    attendance: 96,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Dancing", "Photography"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Dev Raj",
    class: 11,
    age: 16,
    gender: "Male",
    rollNo: 143,
    city: "Chandigarh",
    marks: { math: 92, physics: 90, chemistry: 88, english: 84 },
    totalMarks: 354,
    percentage: 88.5,
    grade: "A",
    attendance: 93,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Cricket", "Coding"],
    skills: ["Programming", "Leadership"]
  },

  {
    name: "Mansi Jain",
    class: 12,
    age: 17,
    gender: "Female",
    rollNo: 144,
    city: "Indore",
    marks: { math: 98, physics: 96, chemistry: 94, english: 97 },
    totalMarks: 385,
    percentage: 96.25,
    grade: "A+",
    attendance: 100,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Chess"],
    skills: ["Research", "Problem Solving"]
  },

  {
    name: "Vivek Singh",
    class: 8,
    age: 13,
    gender: "Male",
    rollNo: 145,
    city: "Haldwani",
    marks: { math: 80, science: 83, english: 78, hindi: 82 },
    totalMarks: 323,
    percentage: 80.75,
    grade: "A",
    attendance: 88,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Cycling"],
    skills: ["Teamwork", "Communication"]
  },

  {
    name: "Aditi Joshi",
    class: 7,
    age: 12,
    gender: "Female",
    rollNo: 146,
    city: "Nainital",
    marks: { math: 86, science: 89, english: 91, hindi: 85 },
    totalMarks: 351,
    percentage: 87.75,
    grade: "A",
    attendance: 95,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Painting", "Reading"],
    skills: ["Creativity", "Communication"]
  },

  {
    name: "Rohit Sharma",
    class: 10,
    age: 15,
    gender: "Male",
    rollNo: 147,
    city: "Delhi",
    marks: { math: 71, science: 75, english: 69, hindi: 78 },
    totalMarks: 293,
    percentage: 73.25,
    grade: "B",
    attendance: 82,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Cricket", "Gaming"],
    skills: ["Teamwork"]
  },

  {
    name: "Anjali Rawat",
    class: 9,
    age: 14,
    gender: "Female",
    rollNo: 148,
    city: "Khatima",
    marks: { math: 93, science: 95, english: 89, hindi: 92 },
    totalMarks: 369,
    percentage: 92.25,
    grade: "A+",
    attendance: 97,
    subjects: ["Math", "Science", "English", "Hindi"],
    hobbies: ["Singing", "Reading"],
    skills: ["Leadership", "Communication"]
  },

  {
    name: "Abhishek Verma",
    class: 12,
    age: 18,
    gender: "Male",
    rollNo: 149,
    city: "Noida",
    marks: { math: 89, physics: 85, chemistry: 91, english: 88 },
    totalMarks: 353,
    percentage: 88.25,
    grade: "A",
    attendance: 91,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Coding", "Football"],
    skills: ["Programming", "Problem Solving"]
  },

  {
    name: "Ritika Singh",
    class: 11,
    age: 16,
    gender: "Female",
    rollNo: 150,
    city: "Dehradun",
    marks: { math: 94, physics: 91, chemistry: 96, english: 93 },
    totalMarks: 374,
    percentage: 93.5,
    grade: "A+",
    attendance: 99,
    subjects: ["Math", "Physics", "Chemistry", "English"],
    hobbies: ["Reading", "Dancing"],
    skills: ["Research", "Leadership"]
  }
])